# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sinatra-snap"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bcarlso", "yaroslav0rudenok"]
  s.date = "2013-03-12"
  s.email = "bcarlso@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/snap_example.rb",
    "lib/sinatra/snap.rb",
    "sinatra-snap.gemspec",
    "spec/snap_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/bcarlso/snap"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Sinatra Named Path support"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

